.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FANCYLOGIN 1 "July  8, 2000"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fancylogin \- fancy console login program
.SH SYNOPSIS
.B fancylogin
.br
.B mingetty.fancylogin tty
.SH DESCRIPTION
This manual page documents briefly the
.B fancylogin
and
.B mingetty.fancylogin
commands.
.PP
\fBfancylogin\fP is a program that presents you a configureable login
mask for the console. For details on configuration see the fancylogin-
documentation.
.br
\fBmingetty.fancylogin\fP is a slightly changed version of the well
known \fBmingetty(8)\fP that calls \fI/bin/fancylogin\fP instead of
\fI/bin/login\fP. So it takes the same arguments.
.SH OPTIONS
\fBfancylogin\fP see \fBlogin(1)\fP
.br
\fBmingetty.fancylogin\fP see \fbmingetty(8)\fP
.SH SEE ALSO
.BR \fBmingetty(8)\fP.
.br
.BR \fBlogin(1)\fP.
.SH AUTHOR
fancylogin is mainly developed by Richard Bergmair. Since version 0.99.6
Andreas Krennmair and Gerfried Fuchs help a lot too, but there are too many
developers of minor patches, beta-testers, and people who just have great
ideas to mention them here.
